services:
  prometheus:
    image: prom/prometheus:v2.53.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml:ro
    ports: ["9090:9090"]

  metrics-generator:
    build: ./generator
    ports: ["8000:8000"]

  alertmanager:
    image: prom/alertmanager:v0.27.0
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports: ["9093:9093"]

  webhook-sink:
    build: ./webhook-sink
    ports: ["8080:8080"]

  grafana:
    image: grafana/grafana-oss:11.1.0
    depends_on: [prometheus]
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=champion123
    ports: ["3000:3000"]
